### ISSUE TITLE
Crash in Meteor

### ISSUE THREAD

**Issue by Hanley1** [the-monochord/cancelandholdattime-polyfill#1]
First off, you should win a nobel prize for making this. I've been waiting forever for Safari and Firefox to support this, as it's needed to make proper envelopes. So thank you.

My app is built on meteor, and importing this polyfill it causes the whole app to crash, with the following error:

`Uncaught TypeError: Cannot read property 'meteorInstall' of undefined`

Apparently this is a generic error that pops up whenever there's an issue with an npm module. Most people solve it by uninstalling the module. Any ideas as to what may be causing this?

**Comment by meszaros-lajos-gyorgy** [comment]
Sorry about not responding for so long, this totally got lost among my inbox messages!

Can you give more info on the nature of your environment? I would like to reproduce this myself, but I need info, like version of meteor and how you add the code to your project ( which method are you using from the ones mentioned in the readme ).

Also, do you happen to have a more detailed log from where your error message is coming from, or is that all you get from meteor?

**Comment by meszaros-lajos-gyorgy** [comment]
I'm closing this, since the discussion is stale and I did not get the necessary information to reproduce this issue.
